//! B191 seed — finite managed-wake runtime and authenticated cancel ownership.
//!
//! Frozen after relocation. Do not edit this file to make the gate green.
//!
//! M1: ignore ReviewRequested.deadlineSecs or make ordinary managed wakes unbounded.
//! M2: let the CLI signal a PID/PGID instead of sending an authenticated request.
//! M3: accept the wrong wake/token, unknown JSON, a blank reason, or a partial frame.
//! M4: allow a late terminal/deadline/cancel candidate to replace the first winner.
//! M5: stop at the deadline without converging the owned provider tree.
//! M6: detach/drop Child or bypass the existing receipt-checked helper-first cleanup.

use std::fs::{self, File};
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};

use orch_host::tierf::TerminationSignal;
use orch_host::wake::{
    managed_wake_runtime_limit, parse_managed_wake_cancel_request,
    select_managed_wake_stop_winner, supervise_managed_child_with_runtime_limit,
    ManagedWakeRuntimeSource, ManagedWakeStopReason, WakeSupervisorPolicy,
    MANAGED_WAKE_MAX_RUNTIME_SECS,
};

const WAKE_ID: &str = "019fc001-1111-4222-8333-444455556666";
const TOKEN: &str = "0123456789abcdef0123456789abcdef";
const REQUEST_ID: &str = "019fc002-aaaa-4bbb-8ccc-ddddeeeeffff";

fn temp_root(label: &str) -> PathBuf {
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = std::env::temp_dir().join(format!(
        "orch-b191-{label}-{}-{nonce}",
        std::process::id()
    ));
    fs::create_dir_all(&root).unwrap();
    root
}

fn policy() -> WakeSupervisorPolicy {
    WakeSupervisorPolicy {
        natural_exit_grace_ms: 30,
        term_grace_ms: 30,
        poll_interval_ms: 5,
    }
}

fn spawn_logged(root: &Path, body: &str) -> (Child, PathBuf) {
    let log_path = root.join("wake.jsonl");
    let stdout = File::create(&log_path).unwrap();
    let stderr = stdout.try_clone().unwrap();
    let child = Command::new("/bin/sh")
        .args(["-c", body])
        .stdin(Stdio::null())
        .stdout(Stdio::from(stdout))
        .stderr(Stdio::from(stderr))
        .process_group(0)
        .spawn()
        .unwrap();
    (child, log_path)
}

#[test]
fn review_deadline_and_ordinary_wake_both_resolve_to_finite_limits() {
    let ordinary = managed_wake_runtime_limit(None);
    assert_eq!(ordinary.requested_review_deadline_secs, None);
    assert_eq!(ordinary.effective_secs, MANAGED_WAKE_MAX_RUNTIME_SECS);
    assert_eq!(ordinary.source, ManagedWakeRuntimeSource::OrdinaryDefault);

    let review = managed_wake_runtime_limit(Some(1_800));
    assert_eq!(review.requested_review_deadline_secs, Some(1_800));
    assert_eq!(review.effective_secs, 1_800);
    assert_eq!(review.source, ManagedWakeRuntimeSource::ReviewDeadline);

    // B157's lifecycle meaning remains intact: zero disables review-overdue.
    // It does not authorize an unbounded OS child, so custody gets the finite
    // safety fallback while the requested value remains exactly zero.
    let disabled_review_sla = managed_wake_runtime_limit(Some(0));
    assert_eq!(disabled_review_sla.requested_review_deadline_secs, Some(0));
    assert_eq!(
        disabled_review_sla.effective_secs,
        MANAGED_WAKE_MAX_RUNTIME_SECS
    );
    assert_eq!(
        disabled_review_sla.source,
        ManagedWakeRuntimeSource::ReviewDeadlineDisabledFallback
    );

    let capped = managed_wake_runtime_limit(Some(u64::MAX));
    assert_eq!(capped.effective_secs, MANAGED_WAKE_MAX_RUNTIME_SECS);
    assert_eq!(capped.source, ManagedWakeRuntimeSource::ReviewDeadlineCapped);
}

#[test]
fn cancel_request_is_exact_bounded_and_bound_to_one_wake_token() {
    let good = serde_json::json!({
        "version": 1,
        "wakeId": WAKE_ID,
        "token": TOKEN,
        "requestId": REQUEST_ID,
        "reason": "operator requested bounded stop"
    });
    let parsed = parse_managed_wake_cancel_request(
        &serde_json::to_vec(&good).unwrap(),
        WAKE_ID,
        TOKEN,
    )
    .unwrap();
    assert_eq!(parsed.wake_id, WAKE_ID);
    assert_eq!(parsed.token, TOKEN);
    assert_eq!(parsed.request_id, REQUEST_ID);
    assert_eq!(parsed.reason, "operator requested bounded stop");

    let mut wrong_wake = good.clone();
    wrong_wake["wakeId"] = serde_json::json!("019fc003-1111-4222-8333-444455556666");
    assert!(parse_managed_wake_cancel_request(
        &serde_json::to_vec(&wrong_wake).unwrap(),
        WAKE_ID,
        TOKEN,
    )
    .is_err());

    let mut wrong_token = good.clone();
    wrong_token["token"] = serde_json::json!("ffffffffffffffffffffffffffffffff");
    assert!(parse_managed_wake_cancel_request(
        &serde_json::to_vec(&wrong_token).unwrap(),
        WAKE_ID,
        TOKEN,
    )
    .is_err());

    let mut unknown = good.clone();
    unknown["pid"] = serde_json::json!(12345);
    assert!(parse_managed_wake_cancel_request(
        &serde_json::to_vec(&unknown).unwrap(),
        WAKE_ID,
        TOKEN,
    )
    .is_err());

    let mut blank = good.clone();
    blank["reason"] = serde_json::json!("   ");
    assert!(parse_managed_wake_cancel_request(
        &serde_json::to_vec(&blank).unwrap(),
        WAKE_ID,
        TOKEN,
    )
    .is_err());

    let mut newline = good;
    newline["reason"] = serde_json::json!("first\nsecond");
    assert!(parse_managed_wake_cancel_request(
        &serde_json::to_vec(&newline).unwrap(),
        WAKE_ID,
        TOKEN,
    )
    .is_err());
}

#[test]
fn stop_candidate_priority_is_deterministic_and_the_first_winner_is_sticky() {
    assert_eq!(
        select_managed_wake_stop_winner(None, true, true, true, true),
        Some(ManagedWakeStopReason::NaturalExit)
    );
    assert_eq!(
        select_managed_wake_stop_winner(None, false, true, true, true),
        Some(ManagedWakeStopReason::HardDeadline)
    );
    assert_eq!(
        select_managed_wake_stop_winner(None, false, false, true, true),
        Some(ManagedWakeStopReason::ManualCancel)
    );
    assert_eq!(
        select_managed_wake_stop_winner(None, false, false, false, true),
        Some(ManagedWakeStopReason::ExactTerminal)
    );
    assert_eq!(
        select_managed_wake_stop_winner(
            Some(ManagedWakeStopReason::ManualCancel),
            true,
            true,
            false,
            true,
        ),
        Some(ManagedWakeStopReason::ManualCancel)
    );
}

#[test]
fn a_nonterminal_managed_child_is_stopped_and_reaped_at_its_runtime_limit() {
    let root = temp_root("hard-deadline");
    // Finite even if a broken implementation misses the one-second deadline,
    // so a red seed cannot leave an immortal fixture behind.
    let (child, log_path) = spawn_logged(&root, "sleep 5");
    let outcome = supervise_managed_child_with_runtime_limit(
        child,
        "opencode",
        &log_path,
        policy(),
        managed_wake_runtime_limit(Some(1)),
    )
    .unwrap();

    assert!(outcome.hard_deadline_reached);
    assert_eq!(outcome.completion_reason, ManagedWakeStopReason::HardDeadline);
    assert!(!outcome.terminal_seen);
    assert!(!outcome.exited_naturally);
    assert!(outcome.signals.contains(&TerminationSignal::Term));
    assert!(outcome.process_tree_terminated);
    fs::remove_dir_all(root).unwrap();
}
