//! B183 seed — bounded process-group termination convergence (H47).
//!
//! Frozen after relocation. Do not edit this file to make the gate green.
//!
//! M1: restore one-shot KILL -> a late same-PGID member survives the only sweep.
//! M2: treat a successful kill command as death -> fresh-probe proof is bypassed.
//! M3: refresh the verification deadline while the group stays alive -> no bounded result.
//! M4: bypass the shared control kernel from the system wrapper, or record every physical
//!     KILL as a new logical signal -> the real wrapper/compatibility contract regresses.

use std::process::{Command, Stdio};
use std::time::Duration;

#[cfg(unix)]
use std::os::unix::process::{CommandExt, ExitStatusExt};

use orch_host::tierf::{
    terminate_managed_process_group, terminate_managed_process_group_with_control,
    ManagedProcessGroupControl, ManagedTerminationPolicy, TerminationSignal,
};

const TEST_PGID: u32 = 4_000_000_001;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum KillBehavior {
    LateMemberAfterFirstKill,
    NeverDies,
}

#[derive(Debug)]
struct FakeControl {
    now: Duration,
    alive: bool,
    behavior: KillBehavior,
    term_calls: usize,
    kill_calls: usize,
    probe_calls: usize,
    sleep_calls: usize,
}

impl FakeControl {
    fn new(behavior: KillBehavior) -> Self {
        Self {
            now: Duration::ZERO,
            alive: true,
            behavior,
            term_calls: 0,
            kill_calls: 0,
            probe_calls: 0,
            sleep_calls: 0,
        }
    }
}

impl ManagedProcessGroupControl for FakeControl {
    fn monotonic_now(&mut self) -> Duration {
        self.now
    }

    fn group_alive(&mut self, pgid: u32) -> Result<bool, String> {
        assert_eq!(pgid, TEST_PGID);
        self.probe_calls += 1;
        Ok(self.alive)
    }

    fn signal_group(&mut self, pgid: u32, signal: TerminationSignal) -> Result<bool, String> {
        assert_eq!(pgid, TEST_PGID);
        match signal {
            TerminationSignal::Term => {
                self.term_calls += 1;
            }
            TerminationSignal::Kill => {
                self.kill_calls += 1;
                if self.behavior == KillBehavior::LateMemberAfterFirstKill && self.kill_calls >= 2 {
                    self.alive = false;
                }
            }
        }
        // A successful signal syscall is not proof that the group is gone.
        Ok(true)
    }

    fn sleep(&mut self, duration: Duration) {
        self.sleep_calls += 1;
        assert!(
            self.sleep_calls <= 32,
            "termination deadline was refreshed or the loop became unbounded"
        );
        self.now += duration;
    }
}

fn policy(kill_verify_ms: u64, poll_ms: u64) -> ManagedTerminationPolicy {
    ManagedTerminationPolicy {
        term_grace: Duration::ZERO,
        kill_verify: Duration::from_millis(kill_verify_ms),
        poll_interval: Duration::from_millis(poll_ms),
    }
}

#[test]
fn a_late_member_after_the_first_kill_is_swept_again() {
    let mut control = FakeControl::new(KillBehavior::LateMemberAfterFirstKill);
    let evidence =
        terminate_managed_process_group_with_control(TEST_PGID, policy(50, 5), &mut control)
            .unwrap();

    assert!(evidence.process_tree_terminated);
    assert_eq!(
        evidence.signals,
        vec![TerminationSignal::Term, TerminationSignal::Kill]
    );
    assert_eq!(control.term_calls, 1);
    assert_eq!(
        control.kill_calls, 2,
        "one-shot KILL leaves the late member alive"
    );
    assert!(control.probe_calls >= 3);
}

#[test]
fn a_successful_kill_command_is_not_death_without_a_fresh_negative_probe() {
    let mut control = FakeControl::new(KillBehavior::NeverDies);
    let evidence =
        terminate_managed_process_group_with_control(TEST_PGID, policy(0, 5), &mut control)
            .unwrap();

    assert!(!evidence.process_tree_terminated);
    assert_eq!(
        evidence.signals,
        vec![TerminationSignal::Term, TerminationSignal::Kill]
    );
    assert_eq!(control.kill_calls, 1);
    assert!(
        control.probe_calls >= 2,
        "death must be established by a probe after the signal attempt"
    );
}

#[test]
fn a_permanently_live_group_times_out_fail_closed_on_one_fixed_deadline() {
    let mut control = FakeControl::new(KillBehavior::NeverDies);
    let evidence =
        terminate_managed_process_group_with_control(TEST_PGID, policy(50, 10), &mut control)
            .unwrap();

    assert!(!evidence.process_tree_terminated);
    assert!(
        control.kill_calls > 1,
        "verification must re-sweep a live group"
    );
    assert!(control.kill_calls <= 8, "verification must remain bounded");
    assert!(
        control.now <= Duration::from_millis(60),
        "the fixed deadline must not be renewed by a live probe: {:?}",
        control.now
    );
}

#[cfg(unix)]
fn independent_group_alive(pgid: u32) -> Result<bool, String> {
    let target = format!("-{pgid}");
    let status = Command::new("/bin/kill")
        .args(["-0", "--", &target])
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map_err(|error| format!("independent /bin/kill -0 -- {target}: {error}"))?;
    Ok(status.success())
}

#[cfg(unix)]
fn bounded_exact_group_kill(pgid: u32) -> Result<(), String> {
    let target = format!("-{pgid}");
    for attempt in 1..=50 {
        let status = Command::new("/bin/kill")
            .args(["-KILL", "--", &target])
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map_err(|error| {
                format!("exact cleanup /bin/kill -KILL -- {target} attempt {attempt}: {error}")
            })?;
        match independent_group_alive(pgid) {
            Ok(false) => return Ok(()),
            Ok(true) => std::thread::sleep(Duration::from_millis(10)),
            Err(error) => {
                return Err(format!(
                    "exact cleanup probe failed after KILL status={status}: {error}"
                ));
            }
        }
    }
    Err(format!(
        "exact cleanup left process group alive after 50 bounded KILL sweeps: {target}"
    ))
}

#[cfg(unix)]
fn observed_absent(observation: &Result<bool, String>) -> bool {
    match observation {
        Ok(alive) => !*alive,
        Err(_) => false,
    }
}

#[cfg(unix)]
#[test]
fn the_public_system_wrapper_converges_and_preserves_logical_signal_shape() {
    let mut child = Command::new("/bin/sh")
        .arg("-c")
        .arg("trap '' TERM; while :; do sleep 1; done")
        .process_group(0)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    std::thread::sleep(Duration::from_millis(50));

    let pgid = child.id();
    let termination = terminate_managed_process_group(pgid, Duration::from_millis(40));
    let alive_after_call = independent_group_alive(pgid);
    let claimed_dead = termination
        .as_ref()
        .map(|evidence| evidence.process_tree_terminated)
        .unwrap_or(false);
    let cleanup_after_call = if !claimed_dead || !observed_absent(&alive_after_call) {
        Some(bounded_exact_group_kill(pgid))
    } else {
        None
    };
    let wait_result = child.wait();
    let alive_after_reap = independent_group_alive(pgid);
    let cleanup_after_reap = if observed_absent(&alive_after_reap) {
        None
    } else {
        Some(bounded_exact_group_kill(pgid))
    };
    let failure_facts = format!(
        "termination={termination:?}; alive_after_call={alive_after_call:?}; \
         cleanup_after_call={cleanup_after_call:?}; wait={wait_result:?}; \
         alive_after_reap={alive_after_reap:?}; cleanup_after_reap={cleanup_after_reap:?}"
    );

    assert!(termination.is_ok(), "{failure_facts}");
    let evidence = termination.as_ref().unwrap();
    assert_eq!(
        evidence.signals,
        vec![TerminationSignal::Term, TerminationSignal::Kill],
        "{failure_facts}"
    );
    assert!(evidence.process_tree_terminated, "{failure_facts}");
    assert_eq!(
        wait_result.as_ref().ok().and_then(|status| status.signal()),
        Some(9),
        "{failure_facts}"
    );
    assert!(observed_absent(&alive_after_call), "{failure_facts}");
    assert!(observed_absent(&alive_after_reap), "{failure_facts}");
}
