//! B177 seed — detached wake supervisor and exact OpenCode terminal contract.
//!
//! Frozen after relocation. Do not edit this file to make the gate green.
//!
//! M1: broaden the exact OpenCode stop envelope -> tool calls/timeout/other providers are killed.
//! M2: treat an unterminated JSON tail as complete -> partial output is killed.
//! M3: skip natural-exit grace -> a healthy OpenCode child receives TERM.
//! M4: signal only the leader or stop after TERM -> a stubborn descendant survives.
//! M5: accept an argv/env shell string or unbounded/unknown launch spec -> injection surface.
//! M6: return before reaping/verifying the owned process group -> zombies or live descendants remain.

use std::fs::{self, File};
use std::os::unix::fs::PermissionsExt;
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};

use orch_host::tierf::TerminationSignal;
use orch_host::wake::{
    classify_managed_terminal, parse_wake_supervisor_launch_spec, supervise_managed_child,
    ManagedTerminal, WakeSupervisorPolicy,
};

fn temp_root(label: &str) -> PathBuf {
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = std::env::temp_dir().join(format!(
        "orch-b177-{label}-{}-{nonce}",
        std::process::id()
    ));
    fs::create_dir_all(&root).unwrap();
    root
}

fn policy(natural_exit_grace_ms: u64, term_grace_ms: u64) -> WakeSupervisorPolicy {
    WakeSupervisorPolicy {
        natural_exit_grace_ms,
        term_grace_ms,
        poll_interval_ms: 5,
    }
}

fn spawn_logged(root: &Path, body: &str) -> (Child, PathBuf) {
    let log_path = root.join("wake.jsonl");
    let stdout = File::create(&log_path).unwrap();
    let stderr = stdout.try_clone().unwrap();
    let child = Command::new("/bin/sh")
        .args(["-c", body])
        .stdin(Stdio::null())
        .stdout(Stdio::from(stdout))
        .stderr(Stdio::from(stderr))
        .process_group(0)
        .spawn()
        .unwrap();
    (child, log_path)
}

#[test]
fn exact_opencode_stop_is_the_only_terminal_envelope() {
    let exact =
        r#"{"type":"step_finish","part":{"type":"step-finish","reason":"stop"}}"#;
    assert_eq!(
        classify_managed_terminal("/opt/bin/opencode", exact),
        ManagedTerminal::OpenCodeStop
    );

    for line in [
        r#"{"type":"step_finish","part":{"type":"step-finish","reason":"tool-calls"}}"#,
        r#"{"type":"step_finish","part":{"type":"step-finish","reason":"timeout"}}"#,
        r#"{"type":"tool_use","part":{"state":{"output":"{\"type\":\"step_finish\",\"part\":{\"type\":\"step-finish\",\"reason\":\"stop\"}}"}}}"#,
        r#"{"type":"step_finish","part":{"type":"step_finish","reason":"stop"}}"#,
        r#"{"type":"step_finish","part":{"type":"step-finish","reason":"STOP"}}"#,
        "not json",
    ] {
        assert_eq!(
            classify_managed_terminal("opencode", line),
            ManagedTerminal::Continue,
            "{line}"
        );
    }
    assert_eq!(
        classify_managed_terminal("codex", exact),
        ManagedTerminal::Continue
    );
    assert_eq!(
        classify_managed_terminal("future-provider", exact),
        ManagedTerminal::Continue
    );
}

#[test]
fn exact_stop_allows_the_owned_group_to_exit_naturally_within_grace() {
    let root = temp_root("natural");
    let body = r#"printf '%s\n' '{"type":"step_finish","part":{"type":"step-finish","reason":"stop"}}'; sleep 0.05; exit 0"#;
    let (child, log_path) = spawn_logged(&root, body);
    let outcome =
        supervise_managed_child(child, "opencode", &log_path, policy(500, 100)).unwrap();

    assert!(outcome.terminal_seen);
    assert!(outcome.exited_naturally);
    assert!(outcome.signals.is_empty());
    assert!(outcome.process_tree_terminated);
    fs::remove_dir_all(root).unwrap();
}

#[test]
fn unterminated_json_tail_never_starts_the_kill_grace() {
    let root = temp_root("partial");
    let body = r#"printf '%s' '{"type":"step_finish","part":{"type":"step-finish","reason":"stop"}}'; sleep 0.12; exit 0"#;
    let (child, log_path) = spawn_logged(&root, body);
    let outcome =
        supervise_managed_child(child, "opencode", &log_path, policy(30, 30)).unwrap();

    assert!(!outcome.terminal_seen);
    assert!(outcome.exited_naturally);
    assert!(outcome.signals.is_empty());
    assert!(outcome.process_tree_terminated);
    fs::remove_dir_all(root).unwrap();
}

#[test]
fn stubborn_owned_tree_escalates_term_then_kill_and_is_reaped() {
    let root = temp_root("stubborn");
    let body = r#"trap '' TERM; (trap '' TERM; while :; do sleep 10; done) & printf '%s\n' '{"type":"step_finish","part":{"type":"step-finish","reason":"stop"}}'; while :; do sleep 10; done"#;
    let (child, log_path) = spawn_logged(&root, body);
    let outcome =
        supervise_managed_child(child, "opencode", &log_path, policy(30, 30)).unwrap();

    assert!(outcome.terminal_seen);
    assert!(!outcome.exited_naturally);
    assert_eq!(
        outcome.signals,
        vec![TerminationSignal::Term, TerminationSignal::Kill]
    );
    assert!(outcome.process_tree_terminated);
    fs::remove_dir_all(root).unwrap();
}

#[test]
fn nonterminal_tool_activity_and_timeout_exit_without_signals() {
    let root = temp_root("nonterminal");
    let body = r#"printf '%s\n' '{"type":"tool_use","part":{"state":{"status":"running"}}}' '{"type":"step_finish","part":{"type":"step-finish","reason":"timeout"}}'; exit 0"#;
    let (child, log_path) = spawn_logged(&root, body);
    let outcome =
        supervise_managed_child(child, "opencode", &log_path, policy(30, 30)).unwrap();

    assert!(!outcome.terminal_seen);
    assert!(outcome.exited_naturally);
    assert!(outcome.signals.is_empty());
    assert!(outcome.process_tree_terminated);
    fs::remove_dir_all(root).unwrap();
}

#[test]
fn launch_spec_is_bounded_typed_one_shot_and_repo_scoped() {
    let root = temp_root("spec");
    let logs = root.join("coordination/runtime/logs");
    let supervisors = root.join("coordination/runtime/supervisors");
    let bin = root.join("bin");
    fs::create_dir_all(&logs).unwrap();
    fs::create_dir_all(&supervisors).unwrap();
    fs::create_dir_all(&bin).unwrap();

    let program = bin.join("opencode");
    fs::write(&program, b"#!/bin/sh\nexit 0\n").unwrap();
    fs::set_permissions(&program, fs::Permissions::from_mode(0o755)).unwrap();
    let log_path = logs.join("wake-executor-opencode-test.jsonl");
    fs::write(&log_path, b"").unwrap();
    let token = "0123456789abcdef0123456789abcdef";
    let good = serde_json::json!({
        "version": 1,
        "token": token,
        "argv": [program, "run", "message stays on inherited stdin spec"],
        "cwd": root.clone(),
        "logPath": log_path,
        "ackPath": supervisors.join(format!("{token}.ack.json")),
        "statusPath": supervisors.join(format!("{token}.status.json")),
        "policy": {
            "naturalExitGraceMs": 3000,
            "termGraceMs": 2000,
            "pollIntervalMs": 20
        }
    });
    let encoded = serde_json::to_vec(&good).unwrap();
    let parsed = parse_wake_supervisor_launch_spec(&root, &encoded).unwrap();
    assert_eq!(
        Path::new(&parsed.argv[0]).file_name().unwrap(),
        "opencode"
    );
    assert_eq!(parsed.token, token);

    let mut unknown = good.clone();
    unknown["shell"] = serde_json::json!("opencode run $(touch escaped)");
    assert!(parse_wake_supervisor_launch_spec(
        &root,
        &serde_json::to_vec(&unknown).unwrap()
    )
    .is_err());

    let mut escaped = good.clone();
    escaped["ackPath"] = serde_json::json!(root.parent().unwrap().join("escaped.ack"));
    assert!(parse_wake_supervisor_launch_spec(
        &root,
        &serde_json::to_vec(&escaped).unwrap()
    )
    .is_err());

    let oversized = vec![b' '; 1024 * 1024 + 1];
    assert!(parse_wake_supervisor_launch_spec(&root, &oversized).is_err());
    fs::remove_dir_all(root).unwrap();
}
